language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-test2' ]; then cd .. && eval "mv $currentfolder generator-test2" && cd generator-test2; fi

